# Generated by Django 3.1.7 on 2021-04-01 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolios',
            fields=[
                ('PortfolioID', models.AutoField(primary_key=True, serialize=False)),
                ('UnrealizedValue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ApiRef', models.CharField(max_length=50)),
                ('StockID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlists',
            fields=[
                ('WatchlistID', models.AutoField(primary_key=True, serialize=False)),
                ('StockID', models.ManyToManyField(to='api.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=15)),
                ('Usermoney', models.DecimalField(decimal_places=2, default=500000, max_digits=10)),
                ('Userpassword', models.CharField(max_length=50)),
                ('PortfolioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.portfolios')),
                ('WatchlistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.watchlists')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('TransactionID', models.AutoField(primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.IntegerField()),
                ('isSold', models.BooleanField(default=False)),
                ('StockID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberOfStocks', models.IntegerField()),
                ('PortfolioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.portfolios')),
                ('StockID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('LeaderboardID', models.AutoField(primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Unrealizedvalue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Realizedvalue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
