# Generated by Django 3.1.7 on 2021-04-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Userpassword',
        ),
    ]
