# Generated by Django 3.1.7 on 2021-03-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('UserMoney', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UserPassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
