# Generated by Django 3.1.7 on 2021-03-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20210322_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserName',
            field=models.CharField(default='username', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='UserID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
